id: P010490
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:29.710141
source_metadata:
  id: bdr:W1KG9090
  title: གཙང་སྨྱོན་ཧེ་རུ་ཀའི་རྣམ་ཐར།
  author: ''
  volumes:
    d0417cbb9abb4c188c49b9ab36c73235:
      image_group_id: I1KG9114
      title: ''
      volume_number: 1
      total_pages: 339
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
